package com.example.momoni.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.momoni.evenity.UserEnvity;

import com.example.momoni.greendao.UserEnvityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userEnvityDaoConfig;

    private final UserEnvityDao userEnvityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userEnvityDaoConfig = daoConfigMap.get(UserEnvityDao.class).clone();
        userEnvityDaoConfig.initIdentityScope(type);

        userEnvityDao = new UserEnvityDao(userEnvityDaoConfig, this);

        registerDao(UserEnvity.class, userEnvityDao);
    }
    
    public void clear() {
        userEnvityDaoConfig.clearIdentityScope();
    }

    public UserEnvityDao getUserEnvityDao() {
        return userEnvityDao;
    }

}
